# Generated by Django 5.2.7 on 2025-10-25 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('processos', '0003_delete_prazo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(help_text='Data e hora do compromisso', verbose_name='Data e hora')),
                ('tipo', models.CharField(choices=[('forum', '🧑\u200d⚖️ Audiência Fórum'), ('virtual', '💻 Audiência Virtual'), ('atendimento', '📞 Atendimento'), ('sessao', '⚖️ Sessão de Julgamento'), ('conciliacao', '🤝 Mediação / Conciliação'), ('reuniao', '📋 Reunião Estratégica')], max_length=50, verbose_name='Tipo de compromisso')),
                ('local', models.CharField(default='Escritório', max_length=200, verbose_name='Local')),
                ('vara', models.CharField(blank=True, default='', max_length=200, verbose_name='Vara/Fórum')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Opcional se processo estiver preenchido', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compromissos', to='clientes.cliente', verbose_name='Cliente direto')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromissos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('processo', models.ForeignKey(blank=True, help_text='Opcional se cliente estiver preenchido', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audiencias', to='processos.processo', verbose_name='Processo vinculado')),
            ],
            options={
                'verbose_name': 'Compromisso',
                'verbose_name_plural': 'Compromissos',
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='BloqueioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data início')),
                ('data_fim', models.DateField(verbose_name='Data fim')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Opcional para bloqueios de dia todo', null=True, verbose_name='Hora início')),
                ('hora_fim', models.TimeField(blank=True, help_text='Opcional para bloqueios de dia todo', null=True, verbose_name='Hora fim')),
                ('dia_todo', models.BooleanField(default=False, help_text='Bloqueio para o dia inteiro', verbose_name='Dia todo')),
                ('tipo_bloqueio', models.CharField(choices=[('ferias', '🏖️ Férias'), ('congresso', '🎤 Congresso/Evento'), ('treinamento', '📚 Treinamento'), ('pessoal', '👤 Assunto Pessoal'), ('emergencia', '🚨 Emergência'), ('outro', '📌 Outro')], max_length=20, verbose_name='Tipo de bloqueio')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(blank=True, null=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Atualizado em')),
                ('profissional', models.ForeignKey(limit_choices_to={'groups__name': 'advogados'}, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_agenda', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Bloqueio de Agenda',
                'verbose_name_plural': 'Bloqueios de Agenda',
                'ordering': ['-data_inicio', '-data_fim'],
            },
        ),
        migrations.CreateModel(
            name='HorarioAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10, verbose_name='Dia da semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de término')),
                ('duracao_slot', models.IntegerField(default=60, help_text='Duração de cada slot em minutos', verbose_name='Duração do slot')),
                ('max_compromissos', models.IntegerField(default=1, help_text='Máximo de compromissos por slot', verbose_name='Máx. compromissos/slot')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('profissional', models.ForeignKey(limit_choices_to={'groups__name': 'advogados'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atendimento', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Horário de Atendimento',
                'verbose_name_plural': 'Horários de Atendimento',
                'ordering': ['profissional', 'dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LogAudiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_anterior', models.DateTimeField(verbose_name='Data original')),
                ('nova_data', models.DateTimeField(verbose_name='Nova data')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data do registro')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo da alteração')),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável')),
                ('audiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agenda.audiencia')),
            ],
            options={
                'verbose_name': 'Log de alteração',
                'verbose_name_plural': 'Logs de alteração',
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.AddConstraint(
            model_name='audiencia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cliente__isnull', True), ('processo__isnull', False)), models.Q(('cliente__isnull', False), ('processo__isnull', True)), _connector='OR'), name='check_processo_ou_cliente_exclusivos'),
        ),
        migrations.AddConstraint(
            model_name='audiencia',
            constraint=models.UniqueConstraint(condition=models.Q(('processo__isnull', False)), fields=('processo', 'data_hora'), name='unique_compromisso_processo_por_data'),
        ),
        migrations.AddConstraint(
            model_name='audiencia',
            constraint=models.UniqueConstraint(condition=models.Q(('cliente__isnull', False)), fields=('cliente', 'data_hora'), name='unique_compromisso_cliente_por_data'),
        ),
        migrations.AlterUniqueTogether(
            name='horarioatendimento',
            unique_together={('profissional', 'dia_semana')},
        ),
    ]
