# Generated by Django 5.2.3 on 2025-07-06 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAudiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_anterior', models.DateTimeField()),
                ('nova_data', models.DateTimeField()),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('audiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.audiencia')),
            ],
        ),
    ]
