# Generated by Django 5.2.3 on 2025-07-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_notificacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
