# Generated by Django 5.2.3 on 2025-07-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_delete_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencia',
            name='vara',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
