# Generated by Django 5.2.3 on 2025-07-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_audiencia_vara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiencia',
            name='vara',
            field=models.CharField(default='Não informado', max_length=200),
        ),
    ]
