# Generated by Django 5.2.3 on 2025-07-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_audiencia_vara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiencia',
            name='tipo',
            field=models.CharField(choices=[('forum', '🧑\u200d⚖️ Audiência Fórum'), ('virtual', '💻 Audiência Virtual'), ('atendimento', '📞 Atendimento'), ('sessao', '⚖️ Sessão de Julgamento'), ('conciliacao', '🤝 Mediação / Conciliação'), ('reuniao', '📋 Reunião Estratégica')], max_length=50),
        ),
    ]
