# Generated by Django 5.2.3 on 2025-07-27 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_audiencia_tipo'),
        ('clientes', '0001_initial'),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencia',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audiencias', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audiencias', to='processos.processo'),
        ),
    ]
