# Generated by Django 5.2.5 on 2025-08-13 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_audiencia_cliente_alter_audiencia_processo'),
    ]

    operations = [
    ]
