# Generated by Django 5.2.5 on 2025-08-13 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_auto_20250813_1915'),
        ('clientes', '0001_initial'),
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiencia',
            options={'ordering': ['data_hora'], 'verbose_name': 'Compromisso', 'verbose_name_plural': 'Compromissos'},
        ),
        migrations.AlterModelOptions(
            name='logaudiencia',
            options={'ordering': ['-data_alteracao'], 'verbose_name': 'Log de alteração', 'verbose_name_plural': 'Logs de alteração'},
        ),
        migrations.AddField(
            model_name='audiencia',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='audiencia',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromissos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='logaudiencia',
            name='motivo',
            field=models.TextField(blank=True, verbose_name='Motivo da alteração'),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Opcional se processo estiver preenchido', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compromissos', to='clientes.cliente', verbose_name='Cliente direto'),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='data_hora',
            field=models.DateTimeField(help_text='Data e hora do compromisso', verbose_name='Data e hora'),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='local',
            field=models.CharField(default='Escritório', max_length=200, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='processo',
            field=models.ForeignKey(blank=True, help_text='Opcional se cliente estiver preenchido', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audiencias', to='processos.processo', verbose_name='Processo vinculado'),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='resultado',
            field=models.TextField(blank=True, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='tipo',
            field=models.CharField(choices=[('forum', '🧑\u200d⚖️ Audiência Fórum'), ('virtual', '💻 Audiência Virtual'), ('atendimento', '📞 Atendimento'), ('sessao', '⚖️ Sessão de Julgamento'), ('conciliacao', '🤝 Mediação / Conciliação'), ('reuniao', '📋 Reunião Estratégica')], max_length=50, verbose_name='Tipo de compromisso'),
        ),
        migrations.AlterField(
            model_name='audiencia',
            name='vara',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Vara/Fórum'),
        ),
        migrations.AlterField(
            model_name='logaudiencia',
            name='alterado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável'),
        ),
        migrations.AlterField(
            model_name='logaudiencia',
            name='audiencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agenda.audiencia'),
        ),
        migrations.AlterField(
            model_name='logaudiencia',
            name='data_alteracao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do registro'),
        ),
        migrations.AlterField(
            model_name='logaudiencia',
            name='data_anterior',
            field=models.DateTimeField(verbose_name='Data original'),
        ),
        migrations.AlterField(
            model_name='logaudiencia',
            name='nova_data',
            field=models.DateTimeField(verbose_name='Nova data'),
        ),
        migrations.AddConstraint(
            model_name='audiencia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cliente__isnull', True), ('processo__isnull', False)), models.Q(('cliente__isnull', False), ('processo__isnull', True)), _connector='OR'), name='check_processo_ou_cliente_exclusivos'),
        ),
        migrations.AddConstraint(
            model_name='audiencia',
            constraint=models.UniqueConstraint(condition=models.Q(('processo__isnull', False)), fields=('processo', 'data_hora'), name='unique_compromisso_processo_por_data'),
        ),
        migrations.AddConstraint(
            model_name='audiencia',
            constraint=models.UniqueConstraint(condition=models.Q(('cliente__isnull', False)), fields=('cliente', 'data_hora'), name='unique_compromisso_cliente_por_data'),
        ),
    ]
