# Generated by Django 5.2.5 on 2025-08-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_alter_audiencia_options_alter_logaudiencia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiencia',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
