# Generated by Django 5.2.3 on 2025-07-05 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('ANDAMENTO', 'Em Andamento'), ('ARQUIVADO', 'Arquivado'), ('CONCLUIDO', 'Concluído')], default='ANDAMENTO', max_length=20)),
                ('area_direito', models.CharField(blank=True, choices=[('TRABALHISTA', 'Trabalhista'), ('CIVIL', 'Cível'), ('FAMILIA', 'Família'), ('TRIBUTARIO', 'Tributário'), ('EMPRESARIAL', 'Empresarial'), ('CRIMINAL', 'Criminal'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='Área de Atuação do Processo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('advogado_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('PETICAO', 'Petição'), ('AUDIENCIA', 'Audiência'), ('SENTENCA', 'Sentença'), ('RECURSO', 'Recurso'), ('OUTROS', 'Outros')], max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='andamentos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Andamento Processual',
                'verbose_name_plural': 'Andamentos Processuais',
                'ordering': ['-data'],
            },
        ),
    ]
