# Generated by Django 5.2.7 on 2025-10-06 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prazos', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Prazo',
                'verbose_name_plural': 'Prazos',
                'ordering': ['data_vencimento'],
            },
        ),
    ]
