# Generated by Django 5.2.7 on 2025-10-24 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_prazo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prazo',
        ),
    ]
