# Generated by Django 5.2.3 on 2025-07-10 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('ativo', models.BooleanField(default=False)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('funcao', models.CharField(choices=[('SEC', 'Secretária'), ('AUX', 'Advogado Auxiliar')], max_length=3)),
                ('advogado_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador_vinculado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('oab', models.CharField(max_length=20)),
                ('endereco_escritorio', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone_escritorio', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_escritorio', models.CharField(blank=True, max_length=101, null=True)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logos_profissionais/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermissaoColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrar_cliente', models.BooleanField(default=False)),
                ('editar_cliente', models.BooleanField(default=False)),
                ('listar_clientes', models.BooleanField(default=False)),
                ('visualizar_cliente', models.BooleanField(default=False)),
                ('excluir_cliente', models.BooleanField(default=False)),
                ('exportar_clientes', models.BooleanField(default=False)),
                ('cadastrar_processo', models.BooleanField(default=False)),
                ('editar_processo', models.BooleanField(default=False)),
                ('listar_processos', models.BooleanField(default=False)),
                ('visualizar_processo', models.BooleanField(default=False)),
                ('excluir_processo', models.BooleanField(default=False)),
                ('atualizar_status_processo', models.BooleanField(default=False)),
                ('ver_agenda', models.BooleanField(default=False)),
                ('adicionar_evento', models.BooleanField(default=False)),
                ('editar_evento', models.BooleanField(default=False)),
                ('excluir_evento', models.BooleanField(default=False)),
                ('editar_audiencias', models.BooleanField(default=False)),
                ('compartilhar_agenda', models.BooleanField(default=False)),
                ('acessar_documentos', models.BooleanField(default=False)),
                ('upload_documento', models.BooleanField(default=False)),
                ('download_documento', models.BooleanField(default=False)),
                ('excluir_documento', models.BooleanField(default=False)),
                ('visualizar_documentos', models.BooleanField(default=False)),
                ('gerenciar_colaboradores', models.BooleanField(default=False)),
                ('configurar_layout', models.BooleanField(default=False)),
                ('visualizar_relatorios', models.BooleanField(default=False)),
                ('colaborador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='usuarios.colaborador')),
            ],
        ),
    ]
