# Generated by Django 5.2.3 on 2025-07-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissaocolaborador',
            name='cadastrar_cliente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='permissaocolaborador',
            name='listar_clientes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='permissaocolaborador',
            name='visualizar_cliente',
            field=models.BooleanField(default=True),
        ),
    ]
