# Generated by Django 5.2.5 on 2025-10-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_permissaocolaborador_cadastrar_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativacao',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
