# Generated by Django 5.2.7 on 2025-10-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_ativacao_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativacao',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
