# Generated by Django 5.2.7 on 2025-10-24 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('processos', '0003_delete_prazo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honorario',
            name='data_vencimento',
        ),
        migrations.RemoveField(
            model_name='honorario',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='honorario',
            name='valor',
        ),
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10)),
                ('usuario_criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_transacao', models.DateField()),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.categoriafinanceira')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.processo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_financeiras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_transacao'],
            },
        ),
        migrations.CreateModel(
            name='ContaAReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('recebido', models.BooleanField(default=False)),
                ('honorario_vinculado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conta_a_receber_honorario', to='financeiro.honorario')),
                ('transacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_a_receber', to='financeiro.transacaofinanceira')),
            ],
            options={
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ContaAPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
                ('transacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_a_pagar', to='financeiro.transacaofinanceira')),
            ],
            options={
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.AddField(
            model_name='honorario',
            name='transacao',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='honorario_transacao', to='financeiro.transacaofinanceira'),
        ),
    ]
