# Generated by Django 5.2.3 on 2025-07-05 20:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo/Razão Social')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator(message='Apenas números são permitidos', regex='^[0-9]*$')], verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(max_length=15)),
                ('area_direito', models.CharField(choices=[('TRABALHISTA', 'Trabalhista'), ('CIVIL', 'Cível'), ('FAMILIA', 'Família'), ('TRIBUTARIO', 'Tributário'), ('EMPRESARIAL', 'Empresarial'), ('CRIMINAL', 'Criminal'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Área de Atuação')),
                ('endereco', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('lgpd_consentimento', models.BooleanField(default=False, verbose_name='Consentimento LGPD')),
                ('advogado_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Advogado Responsável')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
